---
name: Build Test

on: [pull_request]

jobs:
  build_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/setup-arduino-cli@v1
        with:
          version: "1.8.5"